const list = [
  {
    name: "云识别 - 平面AR",
    thumb: "cloudar.png",
    path: "/cloudar-plane/cloudar-plane",
    desc: "云识别后再次识别平面以放置模型",
    poster: "cloudar.png",
    video: "https://meta.kivisense.com/kivicube-slam-mp-plugin/demo-assets/video/slam.mp4",
  },
  {
    name: "云识别 - 漫游AR",
    thumb: "cloudar.png",
    path: "/cloudar-vio/cloudar-vio",
    desc: "云识别后使用漫游AR快速放置模型",
    poster: "cloudar.png",
    video: "https://meta.kivisense.com/wechat-case/video/cloudar-vio.mp4",
  },
  // {
  //   name: "test",
  //   thumb: "cloudar.png",
  //   path: "/cloudar-vio2/cloudar-vio2",
  //   poster: "cloudar.png",
  //   video: "https://meta.kivisense.com/kivicube-slam-mp-plugin/demo-assets/video/panorama-video.mp4",
  // },
  // {
  //   name: "1云识别 - 平面AR",
  //   thumb: "cloudar.png",
  //   path: "/1cloudar-plane/cloudar-plane",
  //   desc: "云识别后再次识别平面以放置模型",
  //   poster: "cloudar.png",
  //   video: "https://meta.kivisense.com/kivicube-slam-mp-plugin/demo-assets/video/slam.mp4",
  // },
  // {
  //   name: "2云识别 - 漫游AR",
  //   thumb: "cloudar.png",
  //   path: "/2cloudar-vio/cloudar-vio",
  //   desc: "云识别后使用漫游AR快速放置模型",
  //   poster: "cloudar.png",
  //   video: "https://meta.kivisense.com/kivicube-slam-mp-plugin/demo-assets/video/glow.mp4",
  // },
  // {
  //   name: "3test",
  //   thumb: "cloudar.png",
  //   path: "/3cloudar-vio2/cloudar-vio2",
  //   poster: "cloudar.png",
  //   video: "https://meta.kivisense.com/kivicube-slam-mp-plugin/demo-assets/video/panorama-video.mp4",
  // },
  // {
  //   name: "4云识别 - 平面AR",
  //   thumb: "cloudar.png",
  //   path: "/4cloudar-plane/cloudar-plane",
  //   desc: "云识别后再次识别平面以放置模型",
  //   poster: "cloudar.png",
  //   video: "https://meta.kivisense.com/kivicube-slam-mp-plugin/demo-assets/video/slam.mp4",
  // },
  // {
  //   name: "5云识别 - 漫游AR",
  //   thumb: "cloudar.png",
  //   path: "/5cloudar-vio/cloudar-vio",
  //   desc: "云识别后使用漫游AR快速放置模型",
  //   poster: "cloudar.png",
  //   video: "https://meta.kivisense.com/kivicube-slam-mp-plugin/demo-assets/video/glow.mp4",
  // },
  // {
  //   name: "6test",
  //   thumb: "cloudar.png",
  //   path: "/6cloudar-vio2/cloudar-vio2",
  //   poster: "cloudar.png",
  //   video: "https://meta.kivisense.com/kivicube-slam-mp-plugin/demo-assets/video/panorama-video.mp4",
  // },
  // {
  //   name: "4AR识别 - 平面AR放置",
  //   thumb: "cloudar.png",
  //   path: "/cloudar-v1/cloudar-v1",
  //   desc: "描述文字描述描述文字文字描述文字描述描述文字文字",
  // },
  // {
  //   name: "5AR识别 - 平面AR放置",
  //   thumb: "cloudar.png",
  //   path: "/cloudar-v1/cloudar-v1",
  // },
];

export default list;
